Adapt to pymatgen 2023.07.20 update.
CederGroupHub/smol pull request #393
Opened 2023-07-23 04:25 UTC by qchempku2017

…s failed.

## Summary

* Add support to pymatgen 2023.07.20
* [issue] test_orbits/test_fixed_values now fails because licabr_orbit's symmetry operation is now 24 instead of 12. Need to figure this out!

## Additional dependencies introduced (if any)

## TODO (if any)

## Checklist

- [ ] Code is in the [standard Python style](https://www.python.org/dev/peps/pep-0008/).
      Run [pycodestyle](https://pycodestyle.readthedocs.io/en/latest/) and [flake8](http://flake8.pycqa.org/en/latest/)
      on your local machine.
- [ ] Docstrings have been added in the [Google docstring format](https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html).
      Run [pydocstyle](http://www.pydocstyle.org/en/2.1.1/index.html) on your code.
- [ ] Tests have been added for any new functionality or bug fixes.
- [ ] All existing tests pass.

2023-07-23 17:00 UTC, lbluque commented
Perhaps the issue with the number of symmetry operations is related to this  some months ago materialsproject/pymatgen#2727

2023-07-23 18:59 UTC, lbluque commented
> Perhaps the issue with the number of symmetry operations is related to this PR made some months ago [materialsproject/pymatgen#2727](https://github.com/materialsproject/pymatgen/pull/2727)

Submitting a bug fix, see materialsproject/pymatgen#3179

2023-07-23 20:27 UTC, qchempku2017 commented
> Perhaps the issue with the number of symmetry operations is related to this PR made some months ago [materialsproject/pymatgen#2727](https://github.com/materialsproject/pymatgen/pull/2727)

Wonderful! Thank you so much for taking care of this!

2023-07-24 23:19 UTC, lbluque requested changes

2023-07-24 23:19 UTC, lbluque commented on requirements.txt
> +pymatgen==2023.07.20
can you remove this pin, we will have to wait to the next release so the symmetry errors are fixed

2023-07-24 23:19 UTC, lbluque commented on tests/test_cofe/test_orbit.py
> +    # TODO: figure out this failure.
remove this comment pls

2023-08-14 15:46 UTC, lbluque commented
Thanks a lot @qchempku2017 !

2023-08-14 22:29 UTC, merged